'use strict'

// Generates ecosystem.config.js from config/site.deploy
// starts PM2 processes and exits

const path = require('path')
const fs = require('fs')
const { execFileSync } = require('child_process')
const { deploy, exampleDir } = require('./backend/site')

const ecosystemPath = path.join(exampleDir, 'deploy', 'ecosystem.config.js')

const buildApps = () => {
  const { script, roles, ...pm2Defaults } = deploy.pm2
  const env = { MDK_DISCOVERY: deploy.discovery }
  return roles.map((role) => ({
    ...pm2Defaults,
    name: role,
    script: path.join(exampleDir, script),
    args: ['--role', role],
    cwd: exampleDir,
    env
  }))
}

const writeEcosystemConfig = (apps) => {
  fs.mkdirSync(path.dirname(ecosystemPath), { recursive: true })
  fs.writeFileSync(
    ecosystemPath,
    `// Auto-generated by start.js from config/site.deploy.json — do not edit directly.\nmodule.exports = ${JSON.stringify({ apps }, null, 2)}\n`
  )
}

const main = () => {
  const apps = buildApps()
  writeEcosystemConfig(apps)
  console.log(`wrote ${path.relative(exampleDir, ecosystemPath)}`)

  execFileSync('pm2', ['start', ecosystemPath], { stdio: 'inherit', cwd: exampleDir })
  console.log(`PM2 processes started — open http://localhost:${deploy.gateway.port}/ once \`pm2 list\` shows all apps online`)
}

main()
