/**
 * Pre-seeded page — ships with the mdk-ui-shell template but is removable.
 * Carries the marker below (do not delete) so the CLI treats this like a file
 * generated by `mdk-ui add page`, i.e. `mdk-ui remove page SiteOverview`
 * unscaffolds it cleanly without needing `--force`.
 */
import { ContainerWidgets, useContainerWidgetsData } from '@tetherto/mdk-react-devkit'
import { useNavigate } from 'react-router'

import { PageLayout } from '../components/PageLayout'
import { buildContainerDetailPath, ROUTE_PATHS } from '../constants/routes'

const SiteOverviewPage = () => {
  const { containers, isLoading, errorMessage } = useContainerWidgetsData()
  const navigate = useNavigate()

  // Clicking a container card deep-links to its detail page, with a backUrl so
  // the detail page's Back link returns here to Site Overview.
  const handleContainerClick = (id: string): void => {
    navigate(buildContainerDetailPath(id, 'home', ROUTE_PATHS.SITE_OVERVIEW))
  }

  return (
    <PageLayout title="Site Overview">
      <ContainerWidgets
        containers={containers}
        isLoading={isLoading}
        errorMessage={errorMessage}
        onContainerClick={handleContainerClick}
      />
    </PageLayout>
  )
}

export default SiteOverviewPage
